FROM node:18-alpine as BUILD_IMAGE

# install pnpm
RUN npm install -g pnpm

WORKDIR /app
COPY package.json pnpm-lock.yaml ./
# install dependencies
RUN pnpm install --frozen-lockfile
COPY . .
# build
RUN yarn build

CMD ["yarn", "dev"]