import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';
import { BadOmenProvider } from '@/contexts/BadOmenContext';
import Hero from '@/components/layout/Hero';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className + ' min-h-screen'}>
        <BadOmenProvider>
          <Navbar />
          <main>
            <Hero />
            <div className="grid grid-cols-none gap-4 px-2 py-4 mx-auto md:grid-cols-4 md:gap-6 md:py-12 md:px-10 md:px-6 lg:px-16 max-w-screen-2xl">
              {children}
            </div>
          </main>
          <Footer />
        </BadOmenProvider>
      </body>
    </html>
  );
}
