import './globals.css'
import {Inter} from 'next/font/google'
import Navbar from "@/components/layout/Navbar"
import Footer from "@/components/layout/Footer";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="pt-br">
        <body className={inter.className + ' min-h-screen'} >
        <Navbar/>
        <main>
            <div
                className="flex justify-center items-center"
                style={{
                    backgroundImage: `url('/img/def_home_hero_bg_image_dark.webp')`,
                    height: '45vh',
                }}
            >
                <button
                    type="button"
                    className="bg-gray-800 bg-opacity-75 items-center px-5 py-3 rounded mx-3"
                >
                    <div>
              <span className="text-gray-100 text-xl font-bold"
              >Join
                <span
                    className="text-light-blue-500 dark:text-light-blue-400 font-extrabold"
                >0</span
                >
                players on minetrax.xinecraft.com</span
              >
                    </div>
                </button>
            </div>
            <div
                className="grid grid-cols-none gap-4 px-2 py-4 mx-auto md:grid-cols-4 md:gap-6 md:py-12 md:px-10 md:px-6 lg:px-16 max-w-screen-2xl"
            >
                {children}
            </div>

        </main>
        <Footer/>
        </body>
        </html>
    )
}
